### ISSUE TITLE
Language switcher

### ISSUE THREAD

**Issue by m-aciek** [python/python-docs-pl#3]
For this translation to make it available through language switcher, following resources [need to be translated](https://www.python.org/dev/peps/pep-0545/#add-translation-to-the-language-switcher):
* [x] [bugs](https://www.transifex.com/python-doc/python-newest/translate/#pl/bugs/) ([published](https://docs.python.org/pl/3/bugs.html)),
* [x] [tutorial/index](https://www.transifex.com/python-doc/python-newest/translate/#pl/tutorial--index/) ([published](https://docs.python.org/pl/3/tutorial/)),
* [x] [tutorial/appetite](https://www.transifex.com/python-doc/python-newest/translate/#pl/tutorial--appetite/) ([published](https://docs.python.org/pl/3/tutorial/appetite.html)),
* [x] [tutorial/interpreter](https://www.transifex.com/python-doc/python-newest/translate/#pl/tutorial--interpreter/) ([published](https://docs.python.org/pl/3/tutorial/interpreter.html)),
* [x] [tutorial/introduction](https://www.transifex.com/python-doc/python-newest/translate/#pl/tutorial--introduction/) ([published](https://docs.python.org/pl/3/tutorial/introduction.html)),
* [x] [tutorial/controlflow](https://www.transifex.com/python-doc/python-newest/translate/#pl/tutorial--controlflow/) ([published](https://docs.python.org/pl/3/tutorial/controlflow.html)),
* [x] [tutorial/datastructures](https://www.transifex.com/python-doc/python-newest/translate/#pl/tutorial--datastructures/) ([published](https://docs.python.org/pl/3/tutorial/datastructures.html)),
* [x] [tutorial/modules](https://www.transifex.com/python-doc/python-newest/translate/#pl/tutorial--modules/) ([published](https://docs.python.org/pl/3/tutorial/modules.html)),
* [x] [tutorial/inputoutput](https://www.transifex.com/python-doc/python-newest/translate/#pl/tutorial--inputoutput/) ([published](https://docs.python.org/pl/3/tutorial/inputoutput.html)),
* [x] [tutorial/errors](https://www.transifex.com/python-doc/python-newest/translate/#pl/tutorial--errors/) ([published](https://docs.python.org/pl/3/tutorial/errors.html)),
* [x] [tutorial/classes](https://www.transifex.com/python-doc/python-newest/translate/#pl/tutorial--classes/) ([published](https://docs.python.org/pl/3/tutorial/classes.html)),
* [x] [tutorial/stdlib](https://www.transifex.com/python-doc/python-newest/translate/#pl/tutorial--stdlib/) ([published](https://docs.python.org/pl/3/tutorial/stdlib.html)),
* [x] [tutorial/stdlib2](https://www.transifex.com/python-doc/python-newest/translate/#pl/tutorial--stdlib2/) ([published](https://docs.python.org/pl/3/tutorial/stdlib2.html)),
* [x] [tutorial/venv](https://www.transifex.com/python-doc/python-newest/translate/#pl/tutorial--venv/) ([published](https://docs.python.org/pl/3/tutorial/venv.html)),
* [x] [tutorial/whatnow](https://www.transifex.com/python-doc/python-newest/translate/#pl/tutorial--whatnow/) ([published](https://docs.python.org/pl/3/tutorial/whatnow.html)),
* [x] [tutorial/interactive](https://www.transifex.com/python-doc/python-newest/translate/#pl/tutorial--interactive/) ([published](https://docs.python.org/pl/3/tutorial/interactive.html)),
* [x] [tutorial/floatingpoint](https://www.transifex.com/python-doc/python-newest/translate/#pl/tutorial--floatingpoint/) ([published](https://docs.python.org/pl/3/tutorial/floatingpoint.html)),
* [x] [tutorial/appendix](https://www.transifex.com/python-doc/python-newest/translate/#pl/tutorial--appendix/) ([published](https://docs.python.org/pl/3/tutorial/appendix.html)),
* [library/functions](https://www.transifex.com/python-doc/python-newest/translate/#pl/library--functions/) ([published](https://docs.python.org/pl/3/library/functions.html)),
  * [x] first column,
  * [ ] second column,
  * [ ] third column,
  * [ ] fourth column.

This issue is to track progress for those resources.

**Comment by StanFromIreland** [comment]
The tutorial-appendix category has been translated.

**Comment by m-aciek** [comment]
Thanks, marked as such.

**Comment by StanFromIreland** [comment]
I'm fairly sure I can get the rest done by then end of the week! Would be great to see it listed as otherwise it is hidden.

**Comment by m-aciek** [comment]
Thank you for your contribution. Please try to review the text produced by machine translation as it tends to not inflect some words properly and not creating correct statements sometimes.

**Comment by StanFromIreland** [comment]
Tutorial what-now is completed and has been reviewed.

**Comment by StanFromIreland** [comment]
Tutorial-stdlib has been translated. I have translated some code strings without accentuation and therefore it looks wrong but I don't know if anything can be done because I checked and Python edition does not include them in its library and throws errors.

**Comment by StanFromIreland** [comment]
Tutorials Classes and Stdlib are 100% complete :) ! Only the Stdlib2 tutorial left and all the functions :( .

**Comment by StanFromIreland** [comment]
Tutorial-Stdlib2 is complete but has not been reviewed at all but I will save that for the distant future.

**Comment by m-aciek** [comment]
> I have translated some code strings without accentuation and therefore it looks wrong but I don't know if anything can be done because I checked and Python edition does not include them in its library and throws errors.

@StanFromIreland [the convention](https://devguide.python.org/documentation/translating/#how-should-i-translate-code-examples) is to translate only string literals, not the names of classes or attributes/variables. Use of accentuation in string literals is safer.

**Comment by StanFromIreland** [comment]
All done now :)

![image](https://github.com/user-attachments/assets/7302cdbc-d77a-4826-96ba-6fe52fe4860a)
