### ISSUE TITLE
Remove left-over files

### ISSUE THREAD

**Issue by m-aciek** [python/python-docs-pl#34]
We have 503 PO files currently in 3.12 branch, whereas gettext build on 3.12 builds 482 PO files only. Automate the process of removing the PO file for translations. To be incorporated with regenerate-tx-config command in the current implementation.

**Comment by rffontenelle** [comment]
Idea: Remove all po files and then pull from Transifex. This way you have only current po files

**Comment by m-aciek** [comment]
I've added a script to warn about files to be deleted and removed files "by hand" locally.

For reference:
* 3.13 15be896d58a142295b3c32cb49e2e61bb02bb5bd
* 3.12 fa628fd30e88140931543022253505455e8b3a10
* 3.11 a757a4bf0fba690065d0999cd250c108f87c1c8c
* 3.10 d550ee25606602e33eab3d56ec94a7c4b86cab6a
* 3.9 d8393d3587498748301c376ce54b00198b3aa7e9
