### ISSUE TITLE
Chart "Postęp tłumaczenia" in ReadMe needs clarification

### ISSUE THREAD

**Issue by StanFromIreland** [python/python-docs-pl#38]
Chart suggests total translation and not % of the goal.

**Comment by m-aciek** [comment]
The chart shows a progress of the "language switcher" resources. The portion required by PEP 545 for a language to be available in the switcher in the left upper corner of the docs site. Maybe a chart title embedded in the image would help avoid confusion?

**Comment by StanFromIreland** [comment]
I think that would be a good idea, also converting it to a line graph rather than the scatter plot to make it clearer?
